# Generated by Django 3.0.8 on 2020-12-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Markets',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('added_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('added_at', models.DateTimeField(auto_now=True)),
                ('num_teams', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('odds', models.FloatField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Markets')),
            ],
        ),
        migrations.AddField(
            model_name='markets',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sports'),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('startTime', models.DateTimeField()),
                ('sport', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Sports')),
            ],
        ),
    ]
