# Generated by Django 3.0.8 on 2020-12-01 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='sport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Sports'),
        ),
        migrations.AlterField(
            model_name='markets',
            name='sport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='core.Sports'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='market',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Markets'),
        ),
    ]
