# Generated by Django 3.0.8 on 2020-12-01 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201201_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='event',
            field=models.ForeignKey(default=994839351788, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Events'),
            preserve_default=False,
        ),
    ]
