# Generated by Django 3.0.8 on 2020-12-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_selection_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
